-- PlanTracker v6 - SQL Updates
-- Adauga liste descrieri pentru SCH, BEW, GEN

INSERT INTO public.list_items (list_name, value, order_index, active) VALUES
  ('desc_sch','Grundriss',1,true),
  ('desc_sch','Schnitte',2,true),
  ('desc_sch','Grundriss + Schnitte',3,true),
  ('desc_sch','Details',4,true),
  ('desc_sch','Rampe',5,true),
  ('desc_sch','Treppenhaus',6,true),
  ('desc_bew','Einzelfundamente',1,true),
  ('desc_bew','Streifenfundamente',2,true),
  ('desc_bew','Zerriegel',3,true),
  ('desc_bew','Aufzugsunterfahrt',4,true),
  ('desc_bew','Winkelstützwand',5,true),
  ('desc_bew','BO_Unten',6,true),
  ('desc_bew','BO_Oben',7,true),
  ('desc_bew','BO_Rand',8,true),
  ('desc_bew','BO_u.+o.',9,true),
  ('desc_bew','BO_u.+r.+o.',10,true),
  ('desc_bew','Decke_u.',11,true),
  ('desc_bew','Decke_o.',12,true),
  ('desc_bew','Decke_r.',13,true),
  ('desc_bew','Decke_u.+o.',14,true),
  ('desc_bew','Decke_u.+r.+o.',15,true),
  ('desc_bew','Decke_Filigran r.+o.',16,true),
  ('desc_bew','Rampe',17,true),
  ('desc_bew','Sturz',18,true),
  ('desc_bew','ST',19,true),
  ('desc_bew','UZ',20,true),
  ('desc_bew','ÜZ',21,true),
  ('desc_bew','Wände',22,true),
  ('desc_bew','Treppen',23,true),
  ('desc_bew','Podest',24,true),
  ('desc_bew','Brüstung',25,true),
  ('desc_bew','Attika',26,true),
  ('desc_bew','Balkon',27,true),
  ('desc_bew','FT-Balkon',28,true),
  ('desc_bew','FT-Podest',29,true),
  ('desc_bew','FT-ST',30,true),
  ('desc_bew','FT-UZ',31,true),
  ('desc_bew','FT-Treppen',32,true),
  ('desc_bew','FT-Decke',33,true),
  ('desc_bew','Kranfundament',34,true),
  ('desc_gen','Model 3D',1,true),
  ('desc_gen','Ajutor pentru coleg',2,true),
  ('desc_gen','Creeare Planliste',3,true),
  ('desc_gen','Creeare Übersicht',4,true),
  ('desc_gen','Verificat Planse',5,true),
  ('desc_gen','Organizare Proiect',6,true),
  ('desc_gen','PDF',7,true),
  ('desc_gen','Citire Statica',8,true),
  ('desc_gen','Trimitere E-mail',9,true),
  ('desc_gen','Planliste Facturare',10,true),
  ('desc_gen','Citire E-mailuri',11,true),
  ('desc_gen','Task Manager',12,true),
  ('desc_gen','Vb cu Beneficiar',13,true),
  ('desc_gen','Discutie sefu',14,true),
  ('desc_gen','Oferta proiect',15,true),
  ('desc_gen','Teleconferinta',16,true),
  ('desc_gen','Medicina muncii',17,true)
ON CONFLICT (list_name, value) DO NOTHING;
